### ISSUE TITLE
Cannot load rxfileio

### ISSUE THREAD

**Issue by daBee** [jrobertson/rxfileio#1]
On `Bundle.require`, I get this error:

```
<internal:/Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- rxfileio (LoadError)
	from <internal:/Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dynarex-daily-0.7.0/lib/dynarex-daily.rb:6:in `<top (required)>'
	from <internal:/Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/chatgpt2023-0.5.1/lib/chatgpt2023.rb:9:in `<top (required)>'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:60:in `require'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:55:in `each'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:44:in `each'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:44:in `require'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler.rb:196:in `require'
	from /Users/user3/zz_before.rb:7:in `<top (required)>'
	from /users/user3/app.rb:10:in `require_relative'
	from /users/user3/app.rb:10:in `<main>'
```

It originally was not installed.  It's not in my `Gemfile.lock`.  

    BUNDLED WITH 2.4.10

    Ruby 3.1.2

**Comment by jrobertson** [comment]
The issue has now been resolved, please update your gems e.g. `ruby do gem update`. The issue was with the ChatGPT2023 which now relies upon the dynarex-daily gem which relies upon the gem rxfileio. However the gem was never added as a dependency to the dynarex-daily gemspec file until now.
Let me know when it is working for you and I will close this issue.

**Comment by daBee** [comment]
OK, looks good.  Onto the next problem.  Heh.
